const express = require("express");
const pgitPolicyRouter = require('./pgitPolicy');
const pgitPolSectionRouter = require('./pgitPolSection');
const PGITPOLRISKADDLINFORouter = require('./PGITPOLRISKADDLINFO');
const pgitPolRiskCoverRouter = require('./pgitPolRiskCover');
const PGITPOLDEDUCTIBLERouter = require('./PGITPOLDEDUCTIBLE');
const pgitPolConditionRouter = require('./pgitPolCondition');
const pgitPolBrokerRouter = require('./pgitPolBroker');
const pgitTaxDtlRouter = require('./pgitTaxDtl');
const pgitPolChargeRouter = require('./pgitPolCharge');
const pgitPolApplCurrRouter = require('./pgitPolApplCurr');
const pgitPolInstPremRouter = require('./pgitPolInstPrem');
const pgitPolPremCompSheetRouter = require('./pgitPolPremCompSheet');
 const pgitAcntDocRouter = require('./pgitAcntDoc');
const router = express.Router();
const lmCompanyRoutes=require('./lmCompanyRoutes');
const class_of_busRoute = require('./class_of_busRoute');
const motorRoute =require('./motorRoute');
const mainTemplateRoute = require("./mainTemplateRoute");
const instancePolicy_01Route = require("./policyInstancesRoute");
const polOneInstCode = require("./policyOneInstCodeRoute");
const oneProgProdInst = require("./oneProgProdeInstRoute");
const listOfInst = require('./listOfInstanceRoute');



router.use('/company',lmCompanyRoutes);
router.use('/businesses', class_of_busRoute);
// router.use('/businesses/motor/programs/PGIT6_01/instances/10-PD-01_01',motorRoute);
router.use('/motor',motorRoute);
router.use('/templates/policy',mainTemplateRoute);
router.use('/policy/instance',instancePolicy_01Route);
router.use('/policy/instanceCode',polOneInstCode);
router.use('/program/product/instance',oneProgProdInst);
router.use('/listOfInst',listOfInst);
router.use('/pgitPolicy', pgitPolicyRouter);
router.use('/pgitPolSection', pgitPolSectionRouter);
router.use('/PGITPOLRISKADDLINFO', PGITPOLRISKADDLINFORouter);
router.use('/pgitPolRiskCover', pgitPolRiskCoverRouter);
router.use('/PGITPOLDEDUCTIBLE', PGITPOLDEDUCTIBLERouter);
router.use('/pgitPolCondition', pgitPolConditionRouter);
router.use('/pgitPolBroker', pgitPolBrokerRouter);
router.use('/pgitTaxDtl', pgitTaxDtlRouter);
router.use('/pgitPolCharge', pgitPolChargeRouter);
router.use('/pgitPolApplCurr', pgitPolApplCurrRouter);
router.use('/pgitPolInstPrem', pgitPolInstPremRouter);
router.use('/pgitPolPremCompSheet', pgitPolPremCompSheetRouter);
router.use('/pgitAcntDoc', pgitAcntDocRouter);
module.exports = router;
