const { sequelize, QueryTypes } = require('../models');

exports.getLov = async () => {
  const query = `
select distinct PLD_MOD_CODE , PLD_PROD_CODE , PLD_SECTION_CODE,PLD_FIELD_NAME, PLD_LOV_TITLE , PLD_LOV_TITLE_BL , PLD_LOV_NO_OF_COLUMN ,PLD_LOV_SELECT_STMT ,PLD_BLOCK_NAME ,PLD_PROG_CODE
from PGIM_LOV_DEFN where PLD_PROG_CODE ='PGIT6_01' AND PLD_MOD_CODE ='10-PD-01_01' AND PLD_BLOCK_NAME = 'PGIT_POLICY'
UNION
select distinct PLD_MOD_CODE , PLD_PROD_CODE , PLD_SECTION_CODE,PLD_FIELD_NAME, PLD_LOV_TITLE , PLD_LOV_TITLE_BL , PLD_LOV_NO_OF_COLUMN ,PLD_LOV_SELECT_STMT ,PLD_BLOCK_NAME ,PLD_PROG_CODE
from PGIM_LOV_DEFN where PLD_PROG_CODE ='PGIT6_01' AND PLD_BLOCK_NAME = 'PGIT_POLICY' AND PLD_MOD_CODE IS NULL `;
  const records = await sequelize.query(query, {
    type: QueryTypes.SELECT,
  });

  return records;
};