const { sequelize, QueryTypes } = require('../models');

exports.get = async () => {
  const query = `SELECT  IFD_INST_CODE "INSTANCE_CODE", IFD_PROG_CODE "PROGRAM_CODE", IFD_PB_BLK_NAME "TABLE_NAME",
IFD_PBF_FLD_NAME "COLUMN_NAME",IFD_PROMPT "FIELD_PROMPT",IFD_SEQ_NO "DISPLAY_ORDER_NO",A.IFD_MANDATORY_YN_NUM "MANDATORY",
IFD_DATA_TYPE "DATA_TYPE",a.ifd_form_item_type "SOURCE_DESIGN_TYPE",IFD_FLD_LEN "FIELD_LENGTH", IFD_DISP_LEN "DISPLAY_LENGTH",    
IFD_HINT "TOOL_TIP"
FROM IM_INSTANCE_FIELD_DEFN A
WHERE IFD_PROG_CODE='PGIT6_03'
AND IFD_PB_BLK_NAME='PGIT_POL_RISK_ADDL_INFO_01'
AND IFD_HIDE_YN_NUM=2
AND IFD_PBF_FLD_NAME NOT LIKE 'M_%' AND IFD_PROMPT IS NOT NULL
AND IFD_CANVAS_NAME='PGIT_POL_RISK_ADDL_INFO_01'
ORDER BY IFD_SEQ_NO;`;
  const records = await sequelize.query(query, {
    type: QueryTypes.SELECT,
  });

  return records;
};