const { sequelize, QueryTypes } = require('../models');

exports.getRiskLov = async () => {
  const query = `
SELECT PLD_MOD_CODE, PLD_PROD_CODE, PLD_SECTION_CODE, PLD_FIELD_NAME, PLD_LOV_TITLE, PLD_LOV_TITLE_BL, PLD_LOV_NO_OF_COLUMN, 
  PLD_LOV_SELECT_STMT, PLD_BLOCK_NAME,PLD_PROG_CODE 
  FROM ( SELECT t.*, ROW_NUMBER() OVER (PARTITION BY PLD_FIELD_NAME ORDER BY PLD_FIELD_NAME) AS rn FROM PGIM_LOV_DEFN t
  WHERE PLD_PROG_CODE = 'PGIT6_03' AND PLD_MOD_CODE = '10-PD-01_01' AND PLD_BLOCK_NAME = 'PGIT_POL_RISK_ADDL_INFO_01'
  UNION ALL
  SELECT t.*, ROW_NUMBER() OVER (PARTITION BY PLD_FIELD_NAME ORDER BY PLD_FIELD_NAME) AS rn FROM PGIM_LOV_DEFN t
  WHERE PLD_PROG_CODE = 'PGIT6_03'  AND PLD_BLOCK_NAME = 'PGIT_POL_RISK_ADDL_INFO_01' AND PLD_MOD_CODE IS NULL)
  WHERE rn = 1;
   `;
  const records = await sequelize.query(query, {
    type: QueryTypes.SELECT,
  });

  return records;
};